In [2]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())

2.13.0+cpu
False


In [3]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(device)

cpu


In [4]:
x = torch.tensor([1, 2, 3])
print(x)
print(type(x))
print(x.shape)
print(x.dtype)
print(x.ndim)


tensor([1, 2, 3])
<class 'torch.Tensor'>
torch.Size([3])
torch.int64
1


In [5]:
print(x.device)

cpu


In [6]:
y = torch.tensor([[1,2,3],
                  [4,5,6]])
y

tensor([[1, 2, 3],
        [4, 5, 6]])

In [7]:
torch.tensor([[1,2,3]]).shape

torch.Size([1, 3])

In [8]:
torch.tensor([
    [1],
    [2],
    [3]
]).shape

torch.Size([3, 1])

In [9]:
a = torch.zeros((3, 4))
b = torch.ones((2, 5))
c = torch.rand((3, 3))
d = torch.arange(0, 10)

In [10]:
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

torch.Size([3, 4])
torch.Size([2, 5])
torch.Size([3, 3])
torch.Size([10])


In [11]:
print(a)
print(b)
print(c)
print(d)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[0.0997, 0.4868, 0.5555],
        [0.5967, 0.3115, 0.7307],
        [0.0607, 0.7851, 0.0742]])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [14]:
x = torch.tensor(3.0, requires_grad=True)
y = x ** 3
y.backward()

In [15]:
print(x.grad)

tensor(27.)
